name: Flutter WorkFlow

on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.1'
          channel: 'stable'
        
      - name: Install dependencies
        run: flutter pub get

      - name: Run Unit Tests
        run: flutter test

      - name: Run Integration Tests
        uses: reactivecircus/android-emulator-runner@v1
        with:
          api-level: 29
          script: flutter drive --target=test_driver/main.dart --driver=test_driver/main_test.dart
