name: Flutter WorkFlow

on:
  push:
   branches: [dev]
    
  pull_request: 
    types: [opened, edited, reopened, synchronize]
    branches: 
     - 'release/*'
     - 'dev*'
     - 'fix/*'
     - 'task/*'
     - 'bug/*'
     - 'feature/*'
     - 'story/*'
     - 'epic/*'
     - 'dev*'

jobs:
  build:
    # runs-on: macos-latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Install Java
      #   uses: actions/setup-java@v2
      #   with:
      #     distribution: 'zulu'
      #     java-version: '11'

      # - name: Install Flutter
      #   uses: subosito/flutter-action@v2
      #   with:
      #     flutter-version: '3.0.1'
      #     channel: 'stable'
      
      # - name: Flutter Doctor
      #   run: flutter doctor -v
        
      # - name: Install dependencies
      #   run: flutter pub get

      # - name: Run Integration Tests
      #   uses: reactivecircus/android-emulator-runner@v2
      #   with:
      #     api-level: 31
      #     target: google_atd
      #     script: flutter drive --target=test_driver/main.dart --driver=test_driver/main_test.dart

      # - name: Upload Screenshoots
      #   uses: peter-evans/create-or-update-comment@v2
      #   with:
      #     issue-number: ${{github.event.pull_request.number}}
      #     body: echo $(./github/scripts/generate-markdown.sh)

      # - name: Run echo path
      #   id: run_path
      #   run: cd .github/ && ls && cd scripts && ls && sudo bash generate-markdown.sh
     
      # - uses: actions/upload-artifact@v2-preview
      #   id: upload_artifacts
      #   with:
      #     name: cypress-screenshots
      #     path: test/failures/*.png
          

          
      # - name: Upload a folder with multiple files
      #   uses: devicons/public-upload-to-imgur@main
      #   id: images_uploads
      #   with:
      #     path: test/failures/
      #     client_id: ${{secrets.IMGUR_CLIENT_ID}}
      # - name: Add reaction
      #   uses: peter-evans/create-or-update-comment@v2
      #   with:
      #     comment-id: 322432 #${{ github.event.comment.id }}
      #     reactions: eyes

      - name: Download
        run: |
          wget https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
      
      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          # body: ${{ steps.images_uploads.outputs.imgur_urls }}
          # comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: 1 #${{ github.event.pull_request.number }}
          body: |
            Commit hello message
            ${{ steps.run_path.outputs.result }}
            ${{ steps.upload_artifacts.outputs.result }}

            ![test1](GitHub-Mark.png)
            ![test2](./GitHub-Mark.png)

           # <img width="300" alt="bunny" src="https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png">
          # token: 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 #${{ secrets.PAT }}
          edit-mode: replace
      
      - name: Hyi
        run: |
          sleep 100000000000


      - name: echo repo
        run: echo "$GITHUB.REPOSITORY"
      
      - name: echo owner
        run: echo "$GITHUB.REPOSITORY_OWNER"
